### ISSUE TITLE
files not found

### ISSUE THREAD

**Issue by harryhoch** [davidnboone/tcga_brca_rnaseq#1]
this file  -https://tcga.xenahubs.net/download/TCGA.BRCA.sampleMap/BRCA_clinicalMatrix - and some others referenced under "Download and decompress the data" seem to be giving 404 errors.

**Comment by davidnboone** [comment]
Thank you for finding this error. I will push a new version soon to correct this. Add .gz to the end of BRCA_clinicalMatrix and it should download properly.

**Comment by harryhoch** [comment]
confirming that addding ".gz" fixes the problem.
