### ISSUE TITLE
Clarify readme for windows anaconda installation

### ISSUE THREAD

**Issue by gabracadabra20** [davidnboone/tcga_brca_rnaseq#3]
When performing a fresh installation of Anaconda on a Windows machine, Jupyter is not added to PATH by default. Might want to specify in readme to include that option or the need to put into PATH. This is important to run the `jupyter notebook` command and when making RKernel visible to Jupyter with the `IRkernel::installspec()` line in R.

**Comment by gabracadabra20** [comment]
With a fresh install on a Windows machine, I needed to install the BiocManager R package before several others would install including tximport, deseq2, and biomaRt. I suggest adding it to the pacman line as the first package.

**Comment by davidnboone** [comment]
Done.
